version: "3.9"

services:
  twitter-uala:
    build:
      context: ./
      dockerfile: Dockerfile
    image: twitter-uala
    container_name: twitter-uala
    restart: on-failure
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"